// 家族族谱 - 公开展示数据
// 本文件由本地编辑模式导出，提交到 GitHub 后访客只能查看，不能在线修改。
const FAMILY_SITE_SETTINGS = {
    "familyName": "窦氏",
    "siteTitle": "窦氏族谱",
    "siteSubtitle": "传承家族记忆，铭记血脉相连",
    "footerText": "窦氏族谱 - 传承窦家血脉，铭记家族历史",
    "accessPassword": "doudoudou"
};

const FAMILY_TREE_DATA = [
    {
        "id": "mqvxqcpluo0w8ittxcp",
        "parentId": null,
        "name": "窦",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 1,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:44:19.161Z"
    },
    {
        "id": "mqvxrlgpt1kj8y8kl5j",
        "parentId": "mqvxqcpluo0w8ittxcp",
        "name": "窦志发",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 2,
        "spouse": "刘茶阁",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:45:17.161Z"
    },
    {
        "id": "mqvxsn1d4f6qxlk42ri",
        "parentId": "mqvxqcpluo0w8ittxcp",
        "name": "窦志勇",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 2,
        "spouse": "刘广芝",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:46:05.857Z"
    },
    {
        "id": "mqvxtfk1pixzpnwpm1a",
        "parentId": "mqvxqcpluo0w8ittxcp",
        "name": "窦相夫",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 2,
        "spouse": "王雪环",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:46:42.817Z"
    },
    {
        "id": "mqvxuampm4u2ykc8xuf",
        "parentId": "mqvxqcpluo0w8ittxcp",
        "name": "窦相臣",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 2,
        "spouse": "吴喜梅",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:47:23.089Z"
    },
    {
        "id": "mqvxv9h5vzk8h66w6zl",
        "parentId": "mqvxrlgpt1kj8y8kl5j",
        "name": "窦胜利",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "冷留娣",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:48:08.249Z"
    },
    {
        "id": "mqvxw6s9rkcf1c9rpsm",
        "parentId": "mqvxrlgpt1kj8y8kl5j",
        "name": "窦胜江",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "郑爱娇",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:48:51.417Z"
    },
    {
        "id": "mqvxxppd9b5abfccxb",
        "parentId": "mqvxrlgpt1kj8y8kl5j",
        "name": "窦莲娥",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:50:02.593Z"
    },
    {
        "id": "mqvxy92xt0lnk7hsbme",
        "parentId": "mqvxsn1d4f6qxlk42ri",
        "name": "窦胜海",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "张桂花",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:50:27.705Z"
    },
    {
        "id": "mqvxyvptblanbcuust6",
        "parentId": "mqvxsn1d4f6qxlk42ri",
        "name": "窦胜红",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "孙红英",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:50:57.041Z"
    },
    {
        "id": "mqvxzchtbnpmgs7bro",
        "parentId": "mqvxsn1d4f6qxlk42ri",
        "name": "窦红美",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:51:18.785Z"
    },
    {
        "id": "mqvy0abl3lysg55ag1j",
        "parentId": "mqvxtfk1pixzpnwpm1a",
        "name": "窦胜桥",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "李税芝",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:52:02.625Z"
    },
    {
        "id": "mqvy12uhr3w4uiptj6t",
        "parentId": "mqvxtfk1pixzpnwpm1a",
        "name": "窦胜全",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "杜莲革",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:52:39.593Z"
    },
    {
        "id": "mqvy1hophwy0nysjhni",
        "parentId": "mqvxtfk1pixzpnwpm1a",
        "name": "窦美娥",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:52:58.825Z"
    },
    {
        "id": "mqvy2fcxgjjvvmwu5wm",
        "parentId": "mqvxuampm4u2ykc8xuf",
        "name": "窦博",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "苗艳艳",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:53:42.465Z"
    },
    {
        "id": "mqvy2sgxvdklhu7tfe",
        "parentId": "mqvxuampm4u2ykc8xuf",
        "name": "窦慧芳",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:53:59.457Z"
    },
    {
        "id": "mqvy33w10uf7jq3i6wuc",
        "parentId": "mqvxuampm4u2ykc8xuf",
        "name": "窦慧春",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 3,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:54:14.257Z"
    },
    {
        "id": "mqvy3qyp96avdmslako",
        "parentId": "mqvxv9h5vzk8h66w6zl",
        "name": "窦英杰",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:54:44.161Z"
    },
    {
        "id": "mqvy3ym10ojblk0qzrj",
        "parentId": "mqvxv9h5vzk8h66w6zl",
        "name": "窦英豪",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:54:54.073Z"
    },
    {
        "id": "mqvy46w9qh3tkq8oht",
        "parentId": "mqvxv9h5vzk8h66w6zl",
        "name": "窦梦娜",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:55:04.809Z"
    },
    {
        "id": "mqvy4oo9rstq4hgczsi",
        "parentId": "mqvxw6s9rkcf1c9rpsm",
        "name": "窦奥运",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:55:27.849Z"
    },
    {
        "id": "mqvy4y7lvm8sx7tkv28",
        "parentId": "mqvxw6s9rkcf1c9rpsm",
        "name": "窦姗姗",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:55:40.209Z"
    },
    {
        "id": "mqvy5czl21jbuni0phh",
        "parentId": "mqvxw6s9rkcf1c9rpsm",
        "name": "窦丹丹",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:55:59.361Z"
    },
    {
        "id": "mqvy6181nodku8diyr",
        "parentId": "mqvxy92xt0lnk7hsbme",
        "name": "窦翱鹏",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:56:30.769Z"
    },
    {
        "id": "mqvy686x10cdehbojzd",
        "parentId": "mqvxy92xt0lnk7hsbme",
        "name": "窦贝贝",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:56:39.801Z"
    },
    {
        "id": "mqvy6e1lbvzkmvjc3k5",
        "parentId": "mqvxyvptblanbcuust6",
        "name": "窦学",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:56:47.385Z"
    },
    {
        "id": "mqvy6m497hoog8a3du7",
        "parentId": "mqvxyvptblanbcuust6",
        "name": "窦楠楠",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:56:57.849Z"
    },
    {
        "id": "mqvy7fzdpplu5hp9s4s",
        "parentId": "mqvy0abl3lysg55ag1j",
        "name": "窦垚",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:57:36.553Z"
    },
    {
        "id": "mqvy7ou9qyfxdets5oa",
        "parentId": "mqvy0abl3lysg55ag1j",
        "name": "窦世康",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:57:48.033Z"
    },
    {
        "id": "mqvy7wmhqy0zvghhbp",
        "parentId": "mqvy0abl3lysg55ag1j",
        "name": "窦静",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:57:58.121Z"
    },
    {
        "id": "mqvy8eax1df3mohe7qr",
        "parentId": "mqvy12uhr3w4uiptj6t",
        "name": "窦世昌",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:58:21.033Z"
    },
    {
        "id": "mqvy8rzl59lkdcu45pq",
        "parentId": "mqvy12uhr3w4uiptj6t",
        "name": "窦晓",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:58:38.769Z"
    },
    {
        "id": "mqvy99axxsqc662sdxl",
        "parentId": "mqvy2fcxgjjvvmwu5wm",
        "name": "窦思允",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:59:01.209Z"
    },
    {
        "id": "mqvy9p9td61v1kl7k4p",
        "parentId": "mqvy2fcxgjjvvmwu5wm",
        "name": "窦思贤",
        "gender": "male",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:59:21.905Z"
    },
    {
        "id": "mqvya2sq3j2d91hheno",
        "parentId": "mqvy2fcxgjjvvmwu5wm",
        "name": "窦思奇",
        "gender": "female",
        "birthYear": null,
        "deathYear": null,
        "generation": 4,
        "spouse": "",
        "notes": "",
        "photo": null,
        "createdAt": "2026-06-27T05:59:39.434Z"
    }
];

const FAMILY_INTRO_TEXT = "窦氏家族源远流长，始祖窦德昌先生（1935-2005）与周淑芬女士共同开创了这一脉家族。历经数代繁衍，窦家枝繁叶茂，人才辈出。本族谱记录了窦氏家族的血脉传承，旨在让后人铭记先辈恩德，传承家族精神。";
